### PR TITLE
doc: add meeting minutes for 30th june 2021

### PR DESCRIPTION
**Pull request by gireeshpunathil**
Fixes: https://github.com/nodejs/diagnostics/issues/481

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by gireeshpunathil** [comment]
landed in 42dcf3ea7ab6edd5d6705b67c2017d0788652435

**Comment by gireeshpunathil** [comment]
I first pushed to the `master` (as opposed to `main`), and removed that commit after realizing the mistake. Not sure if master branch was supposed to be present or not. @mhdawson - do you know if `master` as a branch should exist, or we can delete it?

**Pull request closed without merging**
