### PR TITLE
doc: self nomination to diagnostics WG

### PR DESCRIPTION
**Pull request by legendecas**
Hello everyone, as a Node.js core collaborator, I'd like to nominate myself to diagnostics WG to show my interests on pushing Node.js user diagnostics experience forward :)

### CODE REVIEW

**Comment by mhdawson** [comment]
Added to diag-agenda as Governance says changes to membership should be posted on the WG agenda, once the next meeting complete this can land.

**Comment by gireeshpunathil** [comment]
landed in bedab34f43395655dbb98d0c5de103011b44305b , welcome to the working group!

**Comment by mmarchini** [comment]
I believe someone with admin access needs to invite @legendecas to @nodejs/diagnostics.

**Comment by gireeshpunathil** [comment]
looks like I don't have it, @mhdawson ?

**Comment by gireeshpunathil** [comment]
I just added @legendecas to the diagnostics team.

**Pull request closed without merging**
