### PR TITLE
docs(README): self nomination to diagnostic team

### PR DESCRIPTION
**Pull request by RafaelGSS**
Hello everyone!

Based on #410 and past talks with other members I would like to join to team and help as I can.

### CODE REVIEW

**Comment by Qard** [comment]
Can someone with admin powers at @RafaelGSS to the @nodejs/diagnostics team?

**Comment by mmarchini** [comment]
Just as a reminder, per our governance, this needs to be in the agenda of a meeting:

> Changes to WG membership should be posted in the agenda, and may be suggested as any other agenda item (see "WG Meetings" below).

Not sure if it was discussed today (I don't see it in the notes).

**Comment by RafaelGSS** [comment]
> Not sure if it was discussed today (I don't see it in the notes).

@mmarchini The team commented about this PR [here](https://youtu.be/Alb-zOQrku4?t=869), but I'm not sure if it's the discussion you mentioned.

**Comment by mmarchini** [comment]
Yeah, that should be enough :)

**Comment by gireeshpunathil** [comment]
landed in 9bcdd7cec47b24e18d80636184b0b79e7b966c74

**Comment by Qard** [comment]
Can someone with admin powers add @RafaelGSS to the @nodejs/diagnostics team? I don't have access to add people to teams.

**Comment by mmarchini** [comment]
done

**Pull request closed without merging**
