### PR TITLE
Add list of modules breaking async continuity

### PR DESCRIPTION
**Pull request by watson**
Just starting off the list some some well known sinners 😄 

Not sure if the phrase "async continuity" makes sense to people, but it was the best I could come up with - feel free to suggest something else

### CODE REVIEW

**Comment by jkrems** [comment]
Should we link to existing PRs like https://github.com/petkaantonov/bluebird/pull/1472?

**Comment by watson** [comment]
@jkrems good idea - didn't know there were already a PR. I've updated the table with a link to it.

**Comment by jkrems** [comment]
Good to merge?

**Comment by p-bakker** [comment]
Don't think generic-pool should be on this list: it uses global.Promise by default (so whatever you have installed) and allows to provide the provide the Promise implementation to use through configuration

**Comment by ofrobots** [comment]
It seems that several APMs are monkey-patching `generic-pool` to propagate context:
* Google Cloud's [Stackdriver](https://github.com/googleapis/cloud-trace-nodejs/blob/fae65bd86d3444f2e50254a7f3fe55a55460af8d/src/plugins/plugin-generic-pool.ts).
* Elastic Node.js [agent](https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/generic-pool.js)
* Probably more.

From looking at the patches, it seems that at least `acquire` loses context. If that is still accurate, `generic-pool` belongs on the list.

**Comment by Qard** [comment]
It's mostly because of pre-promise versions of generic-pool, but also because `global.Promise` could be set to _any_ promise implementation, not just the native one, so it _could_ be one not supported by our instrumentation.

**Pull request merged**
